#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

minutes=1
hours=0
while [ $hours -lt 13 ];
do
	echo "Hour: $hours";
	while [ $minutes -lt 60 ];
    do
		echo "$minutes"
        (( minutes++ ))
	done
	minutes=1
    (( hours++ ))
done
