#!/usr/bin/env bash
# Displays in list format the contents of the current directory in.
#   Only displays the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done

