#!/usr/bin/env bash
#A bash script that configures an ubuntu server
#The requirements are as:
# Configure localhost to resolve to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
