#!/usr/bin/env bash
set -e

# Check if Nginx is running
if sudo service nginx status &>/dev/null; then
    sudo service nginx restart
else
    # Stop Nginx before making changes
    sudo service nginx stop

    # Update Nginx configuration to run as nginx user
    echo "user nginx;" >> /etc/nginx/nginx.conf
    sudo chmod 644 /etc/nginx/nginx.conf

    # Change default port to 8080
    sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

    # Start Nginx
    sudo service nginx start
fi
