#!/usr/bin/env bash
sudo service nginx stop
echo "user nginx" | sudo tee -a "/etc/nginx/nginx.conf" >/dev/null
sudo chmod 644 "/etc/nginx/nginx.conf"
sudo sed -i 's/80/8080/g' "/etc/nginx/sites-available/default"
sudo pkill apache2
sudo -u nginx service nginx restart

